apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      hostNetwork: false
      hostPID: false
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsGroup: 3000
      containers:
      - name: api
        image: node:16
        securityContext:
          allowPrivilegeEscalation: false
          allowPrivileges: false
          runAsUser: 1000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: jwt-secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: api-key
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts: []
      volumes: []