name: Ultra-Cheap Security Scan

on:
  pull_request:
    paths:
      - '*.tf'
      - '*.yaml' 
      - '*.yml'
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2  # For git diff

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install boto3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Ultra-Cheap Security Analysis
      run: python security_analyzer_ultra_cheap.py

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('security-results.json')) {
            const results = JSON.parse(fs.readFileSync('security-results.json', 'utf8'));
            
            let comment = `## 💰 Ultra-Cheap Security Scan\n\n`;
            comment += `${results.summary}\n\n`;
            
            if (results.issues.length > 0) {
              results.issues.forEach(issue => {
                comment += `🚨 **${issue.severity.toUpperCase()}** \`${issue.file}\` line ${issue.line}\n`;
                comment += `   ${issue.description}\n\n`;
              });
            }
            
            comment += `💸 **Cost:** $${results.scan_cost} (Monthly: $${results.estimated_monthly_cost})`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }
